services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=microservice.settings
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]